### ISSUE TITLE
Does the embedding-widgets/azure-media-player still work?

### ISSUE THREAD

**Issue by djacobs7** [Azure-Samples/azure-video-indexer-samples#117]
I am looking to build a new front end for some data that is stored in Video Indexer.   I would love to do this in the simplest way possible ( ideally without amp )
 I tried copying the code from `embedding-widgets/azure-media-player` and it doesn't work for me.  Also the videos on this site: [here](https://codepen.io/videoindexer)  don't load. 

Is there an up to date example that takes a publishedUrl  and viewToken and renders the video correctly?

This is what the relevant part of my code looks like

```
            let myPlayer = amp(videoRef.current, {
                "nativeControlsForTouch": false,
                autoplay: true,
                controls: true,
                width: "640",
                height: "360",
                poster: ""
            }, function () {

                myPlayer.src([{
                    src: url,
                    type: "video/mp4",
                    protectionInfo: [{
                        type: "AES",
                        authenticationToken: token
                    }]
                },], []
                );
                console.log(myPlayer)

            });
```

and this is the url: https://api.videoindexer.ai/internals/Trial/Accounts/52558e48-2fc8-445c-98f8-6c699cad1092/Videos/e3b5ac413b/streaming-manifest/manifest.m3u8

The error message I see begins like this:
    The video playback was aborted due to a corruption problem...

Thanks!

**Comment by nofaredanoren** [comment]
Hey @djacobs7,
Since Azure Media player is during deprecation process, we changed our player experience.
You can read more about it here - https://learn.microsoft.com/en-us/azure/azure-video-indexer/azure-video-indexer-azure-media-services-retirement-announcement

In the upcoming week we will update the examples shown here and in our code pen.

Thanks!

**Comment by nofaredanoren** [comment]
Hey @djacobs7 
We have updated our samples and removed azure media player examples.

I recommend reading about how you can embed our widgets in your application-

https://learn.microsoft.com/en-us/azure/azure-video-indexer/video-indexer-embed-widgets?darkschemeovr=1

Thanks
