### ISSUE TITLE
Logic App infrastructure and workload provisioning separation

### ISSUE THREAD

**Issue by cveld** [Azure-Samples/azure-video-indexer-samples#54]
I am considering to separate out the infrastructure part of a logic app from the workload part of a logic app. Comparable to how one would separate out app service infrastructure from workload.

But after some exploration, in particular the key is found in this example file:
https://github.com/Azure-Samples/media-services-video-indexer/blob/master/AIEnrichmentPipeline/infra/logicapp/logicapp.tf

It seems that there is very little separate infrastructure:
```terraform
resource "azurerm_logic_app_workflow" "logicapp" {
  location            = var.shared_env.rg.location
  resource_group_name = var.shared_env.rg.name
  tags                = var.shared_env.tags

  name = var.workflow_name
  lifecycle {
    ignore_changes = [
      # Ignore changes to parameters as otherwise we will break the $connections
      parameters,
      tags
    ]
  }
}
```

The workload seems to contain all infrastructure details as well. I.e.
https://github.com/Azure-Samples/media-services-video-indexer/blob/master/AIEnrichmentPipeline/logicapp/digitaltextfileworkflow/armtemplate.json
specifies the full set of logic app resources.

Why would you keep this terraform resource declaration? 
At least one reason I see, is that terraform provisions the tags towards the logic app resource.

And what about your app lifecycle. Will you run terraform to deploy an updated version of your logic app workload? Is there any suggestion you can make on versioning? Analogous to how one would separate out app service infrastructure from workload package versioning through e.g. Azure Artifacts.

In the past I was involved in a setup where we provide building blocks to use case teams. I.e. we provide a logic app building block and a connection bulding block and the use case team applies these building blocks in their pipelines.
Analogous, you could separate out from the arm template:
* the workload json; reference it from the logic app resource inside terraform
* the connection declaration into terraform
 
Are there any considerations here?

**Comment by shemers** [comment]
This code sample was removed, 
closing the thread.
