### ISSUE TITLE
leading silence, project mode, widget starts at 0 instead of first transcript mark.

### ISSUE THREAD

**Issue by smiles3983** [Azure-Samples/azure-video-indexer-samples#97]
When a recording has alot of leading silence, the first transcript starts at the start of speaking.  My sample recording starts at 50 seconds in.  The insights widget starts at 0 for the first transcript entry.  So the transcript and video are out of sync by 50 seconds when I select a transcript entry or a part in the video.  This is in project scope.  The insights widget should start at the first transcript start time, not always 0.

**Comment by tshaiman** [comment]
Hi @smiles3983  , thanks for submitting this issue .
this repo is aimed for Code Samples on how to use the API , and it is not a Github repo for reporting Video Indexer Bugs and Support requests .

in this page 
https://api-portal.videoindexer.ai/developer-support
![image](https://github.com/Azure-Samples/azure-video-indexer-samples/assets/512709/a8f24724-eeb2-4eee-8315-5198ad1b9132)

you will find several support options , one of them is to open a Ticket to Azure Support .
